#!/bin/bash

#  Creates a installer package for installing Lorica using apple's Installer 
#  application.
#
#  Copyright (C) 2007-2009 OMC Denmark ApS.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

# Install launch deamon
LAUNCH_DIR=$ROOT/Library/LaunchDaemons
mkdir -p $LAUNCH_DIR
cp com.42tools.lorica.plist $LAUNCH_DIR

# Create package
PM_CMD=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker
$PM_CMD --root $ROOT --resources resources --scripts scripts --info Info.plist --version 1.0 --title $APP_NAME --target 10.4 --root-volume-only --out "$DIST/Install $APP_NAME.pkg"
