/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */

/*
 *  Lorica source file.
 *  Copyright (C) 2007-2009 OMC Denmark ApS.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

module Test
{
	interface Receiver {

		/// Receive a call and  send back the number of calls received..
		long  receive_call ();

		/// Get the number of calls that every thread would make...
		long get_call_count ();

	};

	interface Sender {

		/// Ping message..
		void ping ();

		/// Number of active objects trying to use this interface
		oneway void active_objects (in short ao);

		/// Send a ready message
		oneway void send_ready_message (in Receiver callback);
	};
};
