/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */

/*
 *  Lorica source file.
 *  Copyright (C) 2007-2009 OMC Denmark ApS.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

typedef sequence<long> DSI_LongSeq;

struct Structure
{
	short i;
	sequence<long> seq;
};

exception test_exception
{
	short error_code;
	string error_message;
	string status_message;
};

interface Simple_Server
{
	boolean any_test (in any a);

	long struct_test (in long x,
			  in Structure the_in_structure,
			  out Structure the_out_structure,
			  inout string name);

	Object echo_object (in Object obj);

	void raise_user_exception () raises (test_exception);

	void raise_system_exception ();

	oneway void shutdown ();
};
